import { MathQuestion, GradeLevel, Semester, MathTopic } from '../types';
import { jsPDF } from 'jspdf';
import { Document, Packer, Paragraph, TextRun, AlignmentType, Table, TableRow, TableCell, WidthType, BorderStyle } from 'docx';
import saveAs from 'file-saver';

// --- PDF Generation ---

export const exportToPDF = (
  questions: MathQuestion[],
  grade: GradeLevel,
  semester: Semester,
  topic: MathTopic,
  includeAnswers: boolean = false
) => {
  // eslint-disable-next-line new-cap
  const doc = new jsPDF();
  const title = `Primary Math - Grade ${grade} ${semester === Semester.FIRST ? 'Sem 1' : 'Sem 2'}`;
  
  // Note: Standard jsPDF only supports ASCII. For Chinese characters, 
  // you typically need to add a custom font. 
  // To keep this demo portable without external font files, we will use Romanized/English headers 
  // or rely on standard fonts which might display squares for Chinese characters if not configured.
  // Ideally, we would add: doc.addFont('MyFont.ttf', 'MyFont', 'normal');
  // For this output, we will assume standard text for the generated math (numbers are fine).
  // We will try to minimize Chinese in the generated PDF body to avoid encoding issues 
  // in this specific simplified environment, OR we advise the user that Chinese font support requires font loading.
  
  // Fallback: Using simple layout.
  
  doc.setFontSize(18);
  doc.text("Math Practice Worksheet", 105, 20, { align: "center" });
  
  doc.setFontSize(12);
  doc.text(`Level: Grade ${grade} - ${semester}`, 20, 35);
  doc.text(`Topic: ${topic.name} (ID: ${topic.id})`, 20, 42);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 150, 35);
  doc.line(20, 48, 190, 48);

  let y = 60;
  const xLeft = 25;
  const xRight = 115;
  
  questions.forEach((q, index) => {
    // Reset page if needed
    if (y > 270) {
      doc.addPage();
      y = 30;
    }

    const isLeft = index % 2 === 0;
    const x = isLeft ? xLeft : xRight;
    
    // Add number
    doc.setTextColor(100);
    doc.setFontSize(10);
    doc.text(`${index + 1}.`, x - 10, y);
    
    // Add Question
    doc.setTextColor(0);
    doc.setFontSize(12);
    doc.text(q.question, x, y);

    if (includeAnswers) {
        doc.setTextColor(220, 38, 38); // Red
        doc.text(`   ${q.answer}`, x + 50, y);
        doc.setTextColor(0);
    }
    
    // Only increase Y after the right column item (or if it's the last item)
    if (!isLeft || index === questions.length - 1) {
      y += 12; // line height
    }
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount} - Generated by MathGenius AI`, 105, 290, { align: "center" });
  }

  doc.save(`Math_Worksheet_G${grade}_${topic.id}.pdf`);
};

// --- Word Generation ---

export const exportToWord = async (
  questions: MathQuestion[],
  grade: GradeLevel,
  semester: Semester,
  topic: MathTopic,
  includeAnswers: boolean = false
) => {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: "口算练习题",
            heading: "Heading1",
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: `年级: ${grade}年级 ${semester} | 知识点: ${topic.name}`,
            alignment: AlignmentType.CENTER,
            spacing: { after: 300 },
          }),
          // We will create a table for the questions for better layout
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            borders: {
                top: { style: BorderStyle.NONE, size: 0 },
                bottom: { style: BorderStyle.NONE, size: 0 },
                left: { style: BorderStyle.NONE, size: 0 },
                right: { style: BorderStyle.NONE, size: 0 },
                insideVertical: { style: BorderStyle.NONE, size: 0 },
                insideHorizontal: { style: BorderStyle.NONE, size: 0 },
            },
            rows: createWordRows(questions, includeAnswers),
          }),
          new Paragraph({
            text: `生成时间: ${new Date().toLocaleDateString()}`,
            alignment: AlignmentType.RIGHT,
            spacing: { before: 500 },
          })
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `Math_Worksheet_G${grade}_${topic.id}.docx`);
};

function createWordRows(questions: MathQuestion[], includeAnswers: boolean): TableRow[] {
  const rows: TableRow[] = [];
  
  // Pair questions: [0, 1], [2, 3]...
  for (let i = 0; i < questions.length; i += 2) {
    const q1 = questions[i];
    const q2 = questions[i + 1];

    rows.push(
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ 
                children: [
                    new TextRun({ text: `${i+1}.  `, bold: true, color: "888888" }),
                    new TextRun({ text: q1.question + (includeAnswers ? `  ${q1.answer}` : "") })
                ]
            })],
            width: { size: 50, type: WidthType.PERCENTAGE },
          }),
          new TableCell({
            children: q2 ? [new Paragraph({ 
                 children: [
                    new TextRun({ text: `${i+2}.  `, bold: true, color: "888888" }),
                    new TextRun({ text: q2.question + (includeAnswers ? `  ${q2.answer}` : "") })
                ]
            })] : [],
            width: { size: 50, type: WidthType.PERCENTAGE },
          }),
        ],
      })
    );
  }
  return rows;
}